### ISSUE TITLE
remove footer

### ISSUE THREAD

**Issue by AlizayAyesha** [AlizayAyesha/Interactive-Website#11]

**Comment by akadeepesh** [comment]
I'm on it, please assign it to me!

**Comment by YoshithaRathnayake** [comment]
Can you assign me @AlizayAyesha

**Comment by YoshithaRathnayake** [comment]
> I'm on it, please assign it to me!

Can you find a new issue in the site and create the issue then @AlizayAyesha will assign you for sure
Sorry for the inconvenience happened @akadeepesh
